### ISSUE TITLE
All samediff docs need to be added to the new repository.

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j-docs#187]
## Due Date
tbd

## Description
I just added 3 recent docs with #186 . 
Noticed that all of the [samediff docs](https://github.com/eclipse/deeplearning4j/tree/master/docs/samediff/templates) could be missing; 

## Assignees
 tbd (happy to do this if needed.)

**Comment by RobAltena** [comment]
No they don't: "Warning: DO NOT edit the user guide directly in this repository.".

**Comment by saudet** [comment]
Right, we need to edit the templates, and run the scripts to generate the files, but we still need to commit the result here.
