### ISSUE TITLE
Dead Link to Custom Layers

### ISSUE THREAD

**Issue by cric96** [eclipse/deeplearning4j-docs#211]
On the [Custom Layers], the **examples repository** link (at the end of the page) returns 404: 
https://github.com/eclipse/deeplearning4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers

**Comment by treo** [comment]
Thank you for notifying us about that. We've fixed the link so it points to https://github.com/eclipse/deeplearning4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/features/customizingdl4j/layers now
